"""empty message

Revision ID: d91c96cd0a4e
Revises: fa0d5be9ab68
Create Date: 2019-12-10 00:13:14.066418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91c96cd0a4e'
down_revision = 'fa0d5be9ab68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created')
    # ### end Alembic commands ###
